<a href="https://colab.research.google.com/github/vitorpohlenz/python_exercises/blob/list_4/solutions/Exercises_Solutions_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Language

[EN] Please select the language.

[PT] Por favor selecione a linguadem.

In [1]:
# 'PTBR': Português
# 'EN': English
LANGUAGE = 'PTBR'

# Setup

In [2]:
import os
import numpy as np
from IPython.display import Markdown as md # Displaying Markdown as "prints"

<font color = "yellow">[EN] Please do not change the following code! </font>

<font color = "yellow">[PT] Por favor não altere o código abaixo! </font>

In [3]:
!git clone https://github.com/vitorpohlenz/python_exercises.git --branch list_4 --single-branch

Cloning into 'python_exercises'...
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 60 (delta 9), reused 7 (delta 3), pack-reused 38 (from 1)
Receiving objects: 100% (60/60), 45.13 KiB | 1.61 MiB/s, done.
Resolving deltas: 100% (21/21), done.


In [4]:
# Reading Markdown file with the exercises.
with open(f'python_exercises/exercises/List_4_{LANGUAGE}.md','r') as file:
  exercises_raw = file.read()

In [5]:
# Header of the file.
header = exercises_raw.split('## 1')[0]

In [6]:
# Raw string with the questions.
questions_raw = exercises_raw.replace(header,'')

In [7]:
# Putting the questions in to a dict to be displayed.
questions = dict()
for q_string in questions_raw.split(';'):
  if '## ' in q_string:
    q_num = int(q_string.replace('## ','').split('.')[0])
    questions[q_num] = q_string

# Suggested Solutions
[EN] The solutions provided are just suggestions, there are other possible solutions.

For now on <font color = "whitegreen"> feel free to change</font> the code if you want, and <font color = "yellow"> please report any issues!</font>

[PT] As soluções fornecidas aqui são apenas sugestões, existem outras soluções possíveis.

Daqui em diante <font color = "whitegreen"> fique a vontade para modificar</font> o código se quiser, e <font color = "yellow"> por favor reportem qualquer problema!</font>



In [8]:
md(header)

# Exercícios com Numpy: Arrays, ndarrays e Operações Matriciais



> [EN] Note: AS a commom practice for this notebook Numpy is imported as `np`.

> [PT] Nota: Como prática comum, para este notebook o Numpy é importado como `np`.

``` import numpy as np ```

In [9]:
md(questions.get(1))

## 1. Criação de um Array 1D
Crie um array unidimensional (1D) contendo os números de 0 a 9 usando o Numpy. Exiba o array e seu tipo

In [10]:
np_array = np.array(range(10))
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
md(questions.get(2))



## 2. Criação de um Array 2D
Crie um array bidimensional (2D) 3x3 com valores de 1 a 9 usando o Numpy. Exiba a matriz e suas dimensões

In [12]:
np_matrix = np.array([[1,2,3],[4,5,6], [7,8,9]])

print(np_matrix)

print(f"Matrix dims: {np_matrix.shape}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix dims: (3, 3)


In [13]:
md(questions.get(3))



## 3. Operação de Soma em Arrays
Crie dois arrays 1D de tamanho 5, contendo números inteiros aleatórios entre 1 e 10.
Realize a soma entre esses arrays, garanta que os mesmos números aleatórios sejam usados indiferente de quantas vezes o código seja executado

In [14]:
# To keep the same random generation it needs a fixed random_state/seed.
np.random.seed(42)

random_array_1 = np.random.randint(low=1, high=10, size=5)
random_array_2 = np.random.randint(low=1, high=10, size=5)

print(random_array_1)
print(random_array_2)
print(random_array_2 + random_array_1)

[7 4 8 5 7]
[3 7 8 5 4]
[10 11 16 10 11]


In [15]:
md(questions.get(4))



## 4. Operações Matemáticas Elementares
Dado um array 1D de números inteiros de 1 a 5, calcule o quadrado de cada elemento usando operações do Numpy

In [16]:
dummy_array = np.array([1,2,3,4,5])

# Option 1
print(dummy_array**2)

# Option 2
print(np.power(dummy_array, 2))

[ 1  4  9 16 25]
[ 1  4  9 16 25]


In [17]:
md(questions.get(5))



## 5. Multiplicação Matricial
Crie duas matrizes 3x3 de números aleatórios e calcule o produto matricial entre elas usando o método `dot()` do Numpy, utilize também o operador `*` e perceba a diferença

In [18]:
m1 = np.random.randint(low =1 , high=10,size = (3,3))
m2 = np.random.randint(low =1 , high=10, size = (3,3))

print("Matrix 1:\n", m1)
print("Matrix 2:\n", m2)

print("Matricial operation:")

# Option 1
print(m1.dot(m2))

# Option 2
print(m1@m2)

print("Element-wise operation:")
print(m1*m2)

Matrix 1:
 [[8 8 3]
 [6 5 2]
 [8 6 2]]
Matrix 2:
 [[5 1 6]
 [9 1 3]
 [7 4 9]]
Matricial operation:
[[133  28  99]
 [ 89  19  69]
 [108  22  84]]
[[133  28  99]
 [ 89  19  69]
 [108  22  84]]
Element-wise operation:
[[40  8 18]
 [54  5  6]
 [56 24 18]]


In [19]:
md(questions.get(6))



## 6. Transposição de Matriz
Crie uma matriz 4x3 de números aleatórios e calcule sua transposta usando o Numpy

In [20]:
m = np.random.randn(3,3)
print("Matrix: \n",m)
print("Transpose Matrix: \n", m.T)

Matrix: 
 [[ 0.12221917 -0.51543566 -0.60025385]
 [ 0.94743982  0.291034   -0.63555974]
 [-1.02155219 -0.16175539 -0.5336488 ]]
Transpose Matrix: 
 [[ 0.12221917  0.94743982 -1.02155219]
 [-0.51543566  0.291034   -0.16175539]
 [-0.60025385 -0.63555974 -0.5336488 ]]


In [21]:
md(questions.get(7))



## 7. Produto interno usual
O que acontece se utilizar o operador `.dot()` ou `@` entre dois arrays do mesmo tamanho? E entre uma matriz e um array ? Lembre-se de respeitar a coerência entre o número de dimensões da matriz e elementos do array

In [22]:
dummy_array = np.array([1,2,3])
dummy_array2 = np.array([3,2,1])

dummy_matrix = np.array(range(1,10)).reshape(3,3)

print(f"Array_1: {dummy_array}")
print(f"Array 2: {dummy_array2}")
print(f"Matrix :\n{dummy_matrix}")

print("Array_1 @ Array_2 = ", dummy_array @ dummy_array2)

print("Array_1 @ Matrix = ", dummy_array.dot(dummy_matrix))

print("Matrix @ Array_1 = ", dummy_matrix.dot(dummy_array))

Array_1: [1 2 3]
Array 2: [3 2 1]
Matrix :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array_1 @ Array_2 =  10
Array_1 @ Matrix =  [30 36 42]
Matrix @ Array_1 =  [14 32 50]


In [23]:
md(questions.get(8))



## 8. Redimensionamento de Arrays
Crie um array 1D contendo 12 números e redimensione-o para uma matriz 3x4

In [24]:
np.array(range(12)).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
md(questions.get(9))



## 9. Indexação e Slicing
Dada uma matriz 5x5 de números aleatórios, extraia a submatriz 2x2 localizada na parte superior direita

In [26]:
matrix = np.random.randint(low=1, high=10, size=(5,5))
print("Matrix :\n", matrix)

print("Submatrix :\n",matrix[:2, -2:] )

Matrix :
 [[1 4 2 8 4]
 [2 6 6 4 6]
 [2 2 4 8 7]
 [9 8 5 2 5]
 [8 9 9 1 9]]
Submatrix :
 [[8 4]
 [4 6]]


In [27]:
md(questions.get(10))



## 10. Operações Lógicas
Crie um array 1D de 10 números inteiros aleatórios. Verifique quais elementos são maiores que 5 e exiba o resultado como um array booleano e também os valores acima de 5

In [28]:
int_array = np.random.randint(low=1, high=10, size = 10)
bool_array = int_array > 5
print(int_array)
print(bool_array)
print(int_array[bool_array])

[7 9 8 1 8 8 3 1 8 3]
[ True  True  True False  True  True False False  True False]
[7 9 8 8 8 8]


In [29]:
md(questions.get(11))



## 11. Cálculo de Média e Desvio Padrão
Dada uma matriz 4x4 de números inteiros aleatórios, calcule a média e o desvio padrão utilizando todos os elementos

In [30]:
int_matrix = np.random.randint(low=1, high=16, size = (4,4))
print("Matrix:\n", int_matrix)
print("Mean: ", int_matrix.mean())
print("Std: ", int_matrix.std())

Matrix:
 [[ 3  1 11  5]
 [10  7 10  9]
 [12  7  9  8]
 [12  2  1  7]]
Mean:  7.125
Std:  3.6206870894900596


In [31]:
md(questions.get(12))



## 12. Matrizes de Zeros e Uns
Crie uma matriz 5x5 de zeros e outra de uns usando os métodos `zeros()` e `ones()` do Numpy

In [32]:
print("Zeros: \n", np.zeros(shape = (5,5)))
print("Ones: \n", np.ones(shape = (5,5)))

Zeros: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Ones: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
md(questions.get(13))



## 13. Concatenação de Arrays
Crie dois arrays 1D de tamanho 3 e concatene-os tanto horizontalmente quanto verticalmente

In [34]:
a1 = np.array(range(3))
a2 = np.array(range(3,6))

print("Horizontal: ",np.hstack((a1, a2)))
print("Vertical: \n",np.vstack((a1, a2)))

Horizontal:  [0 1 2 3 4 5]
Vertical: 
 [[0 1 2]
 [3 4 5]]


In [35]:
md(questions.get(14))



## 14. Geração de Linspace
Use o método `linspace()` para gerar um array de 10 elementos igualmente espaçados entre 0 e 1. Exiba o array

In [36]:
np.linspace(start = 0, stop = 1, num = 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [37]:
md(questions.get(15))



## 15. Extração de Diagonal de Matriz
Dada uma matriz 4x4 de números aleatórios, extraia os elementos da diagonal principal usando o método `diag()` do Numpy

In [38]:
matrix = np.random.randint(low=1, high=16, size = (4,4))

print("Matrix: \n", matrix)
print("Matrix Diag: \n", np.diag(matrix))

Matrix: 
 [[ 7 14  8  5]
 [ 3 12  8  6]
 [11  3  1  3]
 [ 5 15 14  3]]
Matrix Diag: 
 [ 7 12  1  3]
